rewrite of code

diff --git a/kreate b/kreate
--- a/kreate
+++ b/kreate
@@ -1,39 +1,62 @@
 #!/bin/bash
 
-# Argument Parsing copied from http://mywiki.wooledge.org/BashFAQ/035
+export SILENT
+run=false
+apply=false
 
-die() {
-    printf '%s\n' "$1" >&2
-    exit 1
+
+# Usage info
+show_help() {
+cat << EOF
+Usage: ${0##*/} [options] <dir> ...
+
+The purpose of kreate is to create kostomize files
+based on some generation scripts called kreate.sh
+and then execute kustomize
+
+    -h|--help|help     display this help and exit
+    -v|--verbose       verbose mode.
+    -n|--no-files      do not kreate files
+    -f|--files|files   kreate files (default behaviour)
+    -r|--run|run       run 'kustomize build' (default behaviour)
+    -a|--apply|apply   run 'kustomize build | kubectl apply -f -'
+    -c|--context <ctx> use .kube/config context <ctx> for apply
+    --context=<ctx>    use .kube/config context <ctx> for apply
+EOF
 }
-
-# Initialize all the option variables.
-# This ensures we are not contaminated by variables from the environment.
-file=
-verbose=0
 
 while :; do
     case $1 in
         -h|help|--help)
-            SHOW_HELP=true
-            break
-            ;;
-        -f|--file)       # Takes an option argument; ensure it has been specified.
-            if [ "$2" ]; then
-                file=$2
-                shift
-            else
-                die 'ERROR: "--file" requires a non-empty option argument.'
-            fi
-            ;;
-        --file=?*)
-            file=${1#*=} # Delete everything up to "=" and assign the remainder.
-            ;;
-        --file=)         # Handle the case of an empty --file=
-            die 'ERROR: "--file" requires a non-empty option argument.'
+            show_help
+            exit 0
             ;;
         -v|--verbose)
-            verbose=$((verbose + 1))  # Each -v adds 1 to verbosity.
+            export SILENT=false
+            ;;
+        -n|--no-files)
+            export KREATE_NO_FILES=true
+            ;;
+        -f|--files|files)
+            export KREATE=true
+            ;;
+        -r|--run|run)
+            run=true
+            ;;
+        -a|--apply|apply)
+            apply=true
+            ;;
+        --context=?*)
+            context=${1#*=} # Delete everything up to "=" and assign the remainder.
+            ;;
+        -c|--context)
+            if [ "$2" ]; then
+                context=$2
+                shift
+            else
+                echo 'ERROR: "--context" requires a non-empty option argument.'
+                exit 1
+            fi
             ;;
         --)              # End of all options.
             shift
@@ -48,8 +71,7 @@ while :; do
     shift
 done
 
-declare -A KREATE_PIPE=()
-declare -A KREATE_HELP=()
+KREATE_APPLY_PIPE="kubectl apply -f -"
 
 if [[ -f  ./kreate_profile ]] ;then
   source ./kreate_profile
@@ -59,43 +81,26 @@ elif [[ -f  /etc/kreate/profile ]] ;then
   source /etc/kreate/profile
 fi
 
-# Usage info
-if [[ SHOW_HELP==true ]] ; then
-cat << EOF
-Usage: ${0##*/} [options] APP [command]
-kreate files for APP and apply symbolic command as pipe
-
-    -h|--help  display this help and exit
-    -f|--file OUTFILE
-               write the result to OUTFILE instead of standard output.
-    -v         verbose mode. Can be used multiple times for increased
-               verbosity.
-    command can be any one of:
-EOF
-    for i in "${!KREATE_PIPE[@]}" ; do
-        HELP="${KREATE_HELP[$i]}"
-        if [[ -z "$HELP" ]]; then HELP="${KREATE_PIPE[$i]}"; fi
-        printf "%12s: %s\n" $i "$HELP"
-    done
-    exit
-fi
-
-
-APP=$1
-command=${2-default}
-
-
-for f in \
-    "$KREATE_BASE_DIR/$APP/kreate.sh" \
-    "./$APP/kreate.sh"
+for f in $*
 do
-    if [[ -x $f ]]; then
-        # recreate the base files, should not change anything
-        echo $f
-        $f
+    if [[ -x $f/kreate.sh ]]; then
+        export SILENT
+        export KREATE_NO_FILES
+        $SILENT || echo Starting $f/kreate.sh
+        $f/kreate.sh
+    else
+        $SILENT && echo Skipping $f
+    fi
+    if $apply ; then
+        if [[ -z context ]]; then
+            CONTEXT=""
+        else
+            CONTEXT="--context $context"
+        fi
+        $SILENT || echo kustomize build $f \| $KREATE_APPLY_PIPE $CONTEXT
+        kustomize build $f | $KREATE_APPLY_PIPE $CONTEXT
+    elif $run; then
+        $SILENT || echo running kustomize build $f
+        kustomize build $f
     fi
 done
-
-pipe=${KREATE_PIPE[$command]}
-echo $command == $pipe
-$KREATE_COMMAND $APP | $pipe
